
[config]
additional_profiles = [
  "all-default-tasks",
  "docs-all-modification-tasks",
  "ci-coverage-tasks",
  "ci-all-build-tasks",
  "ci-static-code-analysis-tasks",
  "publish-pre-cleanup",
]

[env]
CARGO_MAKE_SKIP_SLOW_SECONDARY_FLOWS = true

[tasks.clean-target-test-directory]
script = '''
#!@duckscript
rm -Rf ./target/__test
'''

[tasks.pre-test]
dependencies = ["clean-target-test-directory"]
